# Generated by Django 5.1.7 on 2025-04-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_userprofile_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='active', max_length=20),
        ),
    ]
