# Generated by Django 5.2 on 2025-04-28 15:23

from django.db import migrations


def create_admin_user(apps, schema_editor):
    """
    Create a default admin user during migration
    """
    # Get the User model from the apps registry
    User = apps.get_model('auth', 'User')

    # Check if admin user exists
    if not User.objects.filter(username='admin').exists():
        # Create a superuser
        user = User.objects.create(
            username='admin',
            email='admin@example.com',
            is_staff=True,
            is_superuser=True,
            is_active=True
        )
        # Set password (can't use create_superuser with apps.get_model)
        user.set_password('Admin@123456')
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bid_status'),
    ]

    operations = [
        migrations.RunPython(create_admin_user),
    ]
