# Generated by Django 5.2 on 2025-04-28 15:23

from django.db import migrations


def create_admin_user(apps, schema_editor):
    """
    Create a default admin user during migration
    """
    # We can't use the User model directly from apps.get_model
    # because it doesn't include methods like set_password
    from django.contrib.auth import get_user_model
    User = get_user_model()

    # Check if admin user exists
    if not User.objects.filter(username='admin').exists():
        # Create a superuser
        User.objects.create_superuser(
            username='admin',
            email='admin@example.com',
            password='Admin@123456'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bid_status'),
    ]

    operations = [
        migrations.RunPython(create_admin_user),
    ]
