# Generated by Django 5.2 on 2025-04-28 17:11

from django.db import migrations


def create_initial_categories(apps, schema_editor):
    """
    Create initial categories for auctions
    """
    Category = apps.get_model('auctions', 'Category')

    # Create categories only if they don't exist
    categories = [
        'Electronics',
        'Fashion',
        'Home & Garden',
        'Sports',
        'Collectibles',
        'Vehicles',
        'Jewelry',
        'Art',
        'Books',
        'Toys',
        'Antiques',
        'Music',
        'Health & Beauty',
        'Business & Industrial',
    ]

    for category_name in categories:
        Category.objects.get_or_create(name=category_name)


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_create_admin_user'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories),
    ]
