# Generated by Django 5.2 on 2025-05-02 14:03

import auctions.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_create_sample_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=auctions.storage.MediaStorage(location=pathlib.PureWindowsPath('C:/Users/nagar/OneDrive/Desktop/Auction project/Auctoion project/auction_site/media')), upload_to='auction_images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=auctions.storage.MediaStorage(location=pathlib.PureWindowsPath('C:/Users/nagar/OneDrive/Desktop/Auction project/Auctoion project/auction_site/media')), upload_to='profile_images/'),
        ),
    ]
